# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-16 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='out_of_print',
            field=models.BooleanField(default=False),
        ),
    ]
