# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_book_out_of_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='main_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booklist', to='app1.Author'),
        ),
    ]
